### PR TITLE
Added restart computer and empty trashcan to sys plugin

### PR DESCRIPTION
**Pull request by tdoerrich**
I hope the code is good enough. This is my first pull request to an open source project so if you see any issue please PM me with feedback. :) 

I have added some images I got from a royalty free icon website, but if anyone knows where to find better these should be changed.

### CODE REVIEW

**Comment by bao-qian** [comment]
Welcome!
Beside the issue I comment on your code, please reformat your code. 
And it seems you forgot add images to `Wox.Plugin.Sys.csproj` file

**Comment by tdoerrich** [comment]
Okay, will change that and update the script in a few minutes, just gonna finish eating.

**Comment by tdoerrich** [comment]
Okay, working on fixes now. Thanks for the feedback. 

Regarding this though: 2. Why you show a MessageBox and set SHERB_NOCONFIRMATION | RecycleFlag.SHERB_NOPROGRESSUI. MessageBox is redundant if you remove these enum

The reason I did that was to make it more consistent with the overall UI, so instead of showing the Windows UI I had the messagebox show it, like it does when you restart or turn off the computer. :) 

But I will remove that and instead use the built in one if that is better.

**Comment by tdoerrich** [comment]
Pushed an update with the stuff you wrote about. Thanks a lot for the feedback, sorry if the code is a bit weird. As I wrote, only worked on games. I hope this is better.

**Comment by bao-qian** [comment]
Yeah, there is no ru.xaml, I'm little bit unconscious today because of bad sleep last night.

**Comment by tdoerrich** [comment]
Added a check to see if user get's an error when empty trash, and made sure the images are added to the build! :) 

I hope I did it correctly. I've never had to work directly with C# error messages, but I hope I did it properly now.

**Comment by bao-qian** [comment]
This is error code. Not exception.
so the logic should similar as below.

``` c#
if (result != S_OK)
{
    MessageBox.Show($"error bla bla, error code: {result}\n" +
                     "please refer to https://msdn.microsoft.com/en-us/library/windows/desktop/aa378137");
}
```

**Comment by tdoerrich** [comment]
True.  Will fix that  and add hibernate mode as soon as I get home from work today. Should be in about three or four hours.

**Comment by bao-qian** [comment]
no need to hurry :smile:

**Comment by tdoerrich** [comment]
Hmm, I can't seem to figure out how to get error codes to display in the message. At least not without the try and catch (where i catch an exception). Could maybe one of you point me where I need to look to fix that part? Otherwise, I seem to have fixed Hibernate. The only is the error message for the recycling bin.

**Comment by bao-qian** [comment]
What you could do now is close this pr. And then use git rebase to clean your commit. Finally, create a new pr to dev branch. I will fix the rest on that branch then merge it into master.

**Comment by tdoerrich** [comment]
Will do!

**Comment by bao-qian** [comment]
reference: #400

**Pull request closed without merging**
