### PR TITLE
Update Control Panel

### PR DESCRIPTION
**Pull request by CoenraadS**
The Control Panel now also includes third party panel items.

The code is also much more organized now, maybe it won't throw exceptions on your pc anymore (hopefully)

I noticed that you increased the amount of returned results to 5. I didn't change that, but imo it is too high. Perhaps it can become a user setting.

### CODE REVIEW

**Comment by qianlifeng** [comment]
@CoenraadS I find the exception in my computer. And fixed now. 83e45534ff5ed66389f62789dd6da979090f6776

**Comment by CoenraadS** [comment]
@qianlifeng 

Could you tell me what control panel item returns null as an icon?

**Comment by CoenraadS** [comment]
Is that a third party uninstaller?

If so, could you give a website? Thanks

I think I know the problem, its probably in the registry as "Uninstall/Remove programs, clean browser plugins".

While Microsoft states:
"Environment variables can be used as a substitute for a part of the path. The path and file name is followed by a comma (,) and a hyphen (-), followed by the ID in the string table.
If the module does not have a string table, then this entry can simply be the display name string."

I think I just need to change split from `,` to `,-`

**Comment by qianlifeng** [comment]
maybe [http://www.iobit.com/advanceduninstaller.html](http://www.iobit.com/advanceduninstaller.html), I installed advanced systemcare.

**Pull request merged**
