### PR TITLE
Open With Sublime

### PR DESCRIPTION
**Pull request by qiankanglai**
Add one more function to everything (in fact it works with other texteditors, which is configuratable)

### CODE REVIEW

**Comment by jhdxr** [comment]
the codes LGTM.
however, could you change `sublime` to `editor`, and make `notepad` as the default setting since it's always available on Windows.
Thank you.

**Comment by qiankanglai** [comment]
Refactored with general editor support

**Comment by jhdxr** [comment]
merged, thank you

**Comment by galantra** [comment]
Is it possible to change the editor program? I prefer Notepad++ over the default Editor.

**Pull request merged**
