### PR TITLE
added build instructions for VS 2019

### PR DESCRIPTION
**Pull request by itziksi**

### CODE REVIEW

**Comment by bao-qian** [comment]
I think this is no longer the case, checkout https://github.com/Wox-launcher/Wox/tree/dev

**Comment by itziksi** [comment]
Hi,
Thank you for you answer.
Maybe as you wrote, maybe its no longer the case.

Can you tell me what is the status of the project ?
I've added some optimizations, eg usage of suffix-tree to speed up search,
and also file-watchers,
to "refresh" database automatically, but I didnt submit pull-request
because I thought the project is not maintained any more.

Do you plan to check pull-requests in the future ?

Thanks,
Best regards,
Itzik.

**Comment by bao-qian** [comment]
@itziksi 
hi,
this project is active development now, more than 200 commits and several release in a week.
I will check all pr, as you see, all old pr has been merged.

thanks
bao

**Comment by itziksi** [comment]
Hi bao,
Thanks for your email.

I have a question, maybe you can help.
When I started to use the program about 6 months, I was looking for a
plugin to open files in "My Documents" folder.
I couldn't find anything that I liked, and the "Everything" plugin looked
too much.
So I wrote my own plugin, which I use all the time.
I find it very useful because I added "file watcher" so it automatically
index the files in real time,
and also I used "suffix tree" for the search, so search time is
un-noticeable also on slow computer
(I've done many tests using Stopwatch)
Do you have any new way now ?
If not, do you think this can be accepted under your respiratory  ?
( https://github.com/Wox-launcher/Wox/tree/master/Plugins  )

If you think, or even want to check, I can submit the code.
Thanks for your help,
Regards
Itzik.

**Comment by bao-qian** [comment]
Hi Itzik,
 For the file search in windows, I’d suggest using everything plugin. Everything is the fastest file search program in windows.
It has real-time index, and you can limit search scope in everything own setting menu.

Regards
Bao

________________________________

**Pull request closed without merging**
