### PR TITLE
Update Folder plugin (changes from JJW24 fork)

### PR DESCRIPTION
**Pull request by theClueless**
Folder plugin changes - 
- improve code readability.
- added support for share folder (prefix with '\\')
- added context menus
- added the ability to search all paths under a folder using ~ in the query.

### CODE REVIEW

**Comment by bao-qian** [comment]
import feature by feature is good.
what is the latest commit your upstream is based on? 
I guess is the https://github.com/jjw24/Wox/tree/28acd466b352a807910cebbc74477d3173b31511 commit, right?
if so, I think you should mentioned this commit number in your commit message.

**Comment by theClueless** [comment]
I'm not sure I understand what you mean.
Since the fork has started to be really far from the original, I took the original repo dev branch and copy manually some changes but had to do some changes as things has changed in the infrastructure.

**Comment by bao-qian** [comment]
lets' discuss in this pr only.
since you did some changes, could you at least separate this pr into two commit?
for the first commit, just copy the code from latest dev branch, and the commit message should include the latest commit link (https://github.com/jjw24/Wox/commit/1932515fe9844391c2cabacdacffb38912181539) from dev branch. so people know that these code comes from that commit.
for the second commit, it should contains your changes which you mentioned above.

**Comment by bao-qian** [comment]
duplicate
https://github.com/Wox-launcher/Wox/pull/2754#issuecomment-616779191

**Pull request closed without merging**
