### PR TITLE
Project structure refactoring and dependency management

### PR DESCRIPTION
**Pull request by foobarbazmeow**
Yes, I know, a lot of changes. But it looks better now.

Before:
before
After:
2014-05-25 15-12-24 windows 8 1

### CODE REVIEW

**Comment by foobarbazmeow** [comment]
Oopsy, haven't merged 6aed2ec3116dc5e269e9f62988d27b4a00f05c49 and 4c3f51cae3addda1c106044cab97d2dd2364155a. Sorry.

**Comment by qianlifeng** [comment]
Thx for the efforts.

**Comment by qianlifeng** [comment]
@antigravity The Arguments property in Query.cs is a little ambiguity, which I think should not include Command. For a query, e.g. `yd translation`, the command should be `yd` and the `translation` should be the argument of the command. Now `Arguments[0]` is the command and the `Argument[1]` is the real argument. I know it's maybe a semantic difference, it's not a problem for use, but we should try to keep our API easy to understand. @orzFly what's your opinion?
By the way, we should try to avoid changing the API in Wox.Plugins project, unless it's really need to. Any changes to Plugin interface means existing third party plugins will be affected and may be broken by this.
At last, thx for your contributing anyway.

**Comment by foobarbazmeow** [comment]
@qianlifeng 

> The Arguments property in Query.cs is a little ambiguity, which I think should not include Command. For a query, e.g. yd translation, the command should be yd and the translation should be the argument of the command. Now Arguments[0] is the command and the Argument[1] is the real argument. I know it's maybe a semantic difference, it's not a problem for use, but we should try to keep our API easy to understand.

Make sense, maybe we should make it internal/private. 

> By the way, we should try to avoid changing the API in Wox.Plugins project, unless it's really need to. Any changes to Plugin interface means existing third party plugins will be affected and may be broken by this.

True, actually I did not expect that my changes go into the master. Maybe you should place it in vNext branch.

There are several places that bothers me. One of that is plugin loader. We are definitely should use MEF instead of inventing our own wheel. Partly I have already done it. But, yeah, only in next milestone.

**Comment by aaroncampf** [comment]
So are we creating a new branch?

I am still trying to find a good way to enable/disable plugins, but I think this would conflict with any changes I make.

Would these changes have a solution for enabling/disabling plugins?

**Comment by foobarbazmeow** [comment]
> I am still trying to find a good way to enable/disable plugins, but I think this would conflict with any changes I make.
> Would these changes have a solution for enabling/disabling plugins?

Sure, MEF is very flexible.
http://mef.codeplex.com/wikipage?title=Recomposition

**Comment by qianlifeng** [comment]
MEF looks great, maybe we should try that. Does it support .net framework 3.5? Seems we can just reference System.ComponentModel.Composition.dll.

**Comment by foobarbazmeow** [comment]
> MEF looks great, maybe we should try that. Does it support .net framework 3.5?

Yep, https://mef.codeplex.com/releases/view/40606

**Comment by qianlifeng** [comment]
I find a lot of things changed/not work as usual, I need to review those changes carefully.

**Comment by foobarbazmeow** [comment]
@qianlifeng I think this can be close without merge. I'm working on the next version which contains many critical changes that includes these.

**Comment by qianlifeng** [comment]
what's your main focus for the next version?

**Comment by foobarbazmeow** [comment]
@qianlifeng 

> what's your main focus for the next version?

Common plugin ecosystem (based on MEF), UI improvements and a bunch of new plugins of course :yum:

**Comment by qianlifeng** [comment]
@antigravity Sounds great, Do we want to change all existing third-party plugins if we use MEF? Is it possible to support backward compatibility.?

**Comment by foobarbazmeow** [comment]
@qianlifeng Yes, I can keep the old implementation, but it will be marked as obsolete.

**Pull request closed without merging**
