### PR TITLE
Fixes MainWindow.xaml preview

### PR DESCRIPTION
**Pull request by rmterra**
I went through the same problem this week on a project at work =x

We solve by changing the visibility property binding from bool to System.Window.Visibility, this way the preview was not supressed anymore =D

### CODE REVIEW

**Comment by bao-qian** [comment]
@LingForCC what do you think? using this way, we don't need `VisibilityConverter` at all.

**Comment by bao-qian** [comment]
Thanks for your help!

**Comment by LingForCC** [comment]
This is definitely a solution for this problem. The only problem is that it introduces System.Windows namespace into ViewModel, which is not a big deal actually. :) 
Another possible solution is to detect whether we are in designing mode and return a specific value. So our VisibilityConverter looks like as following.

image

What do you guys think?

**Comment by bao-qian** [comment]
why introduce `System.Windows` namespace is a bad idea?

**Comment by LingForCC** [comment]
As my understanding, ViewModel should try it best to support different types of View technology. So if we introduce System.Windows into ViewModel, it is kind of binding with WPF. 
But as I said, it is not a big deal in this case since it is unlikely we will render our ViewModel to other View tech. But it is still a thing to consider.

**Comment by rmterra** [comment]
I had not thought that way but makes a lot of sense, if we want to reuse the view model in another presentation project like mono with gtk that will be a problem =x.

I didn't know the `DesignerProperties` it is really very useful xD

Well, can I revert to my change and implement as @LingForCC indicated?

**Comment by bao-qian** [comment]
No, I think your method is better and clear.
What you can do is remove `VisibilityConverter` and refactoring all `Visibility` binding.
Consistency is the most important principles. 
When you done, open a new PR.

**Comment by bao-qian** [comment]
As you can see in `VisibilityConverter`, we are using `Collapsed` instead of `Hidden`.

**Comment by bao-qian** [comment]
ref: #495

**Comment by rmterra** [comment]
Okidoki o/

**Pull request closed without merging**
