### PR TITLE
Add two Windows 11 Mica themes

### PR DESCRIPTION
**Pull request by walterlv**
## Windows 11 Mica Dark

仿云母材质（暗）

image

## Windows 11 Mica Light

仿云母材质（亮）

image

### CODE REVIEW

**Comment by ahmet-cetinkaya** [comment]
It's something I feel lacking. I hope it will be accepted soon.

**Review by naxl — APPROVED** [review]
Amazing.

**Comment by wanyann** [comment]
very very nice theme, thanks! 
also i made some changes, cause in my opinion, searched text in selected line in different color looks bad. i added:
`<SolidColorBrush x:Key="ItemSelectedHighlightColor" Color="#2E2727"/>` property
with the same color value as in the `ItemHighlightColor` property

**Comment by qianlifeng** [comment]
close since https://github.com/Wox-launcher/Wox/discussions/3937

**Pull request closed without merging**
