### PR TITLE
Change https to http becuase the SSL has expired

### PR DESCRIPTION
**Pull request by bao-qian**

### CODE REVIEW

**Comment by bosam** [comment]
It seems the api is also impacted with https.
wpm install crashes the application. Perhaps, switch the endpoint to http as well?

**Comment by bao-qian** [comment]
@bosam thanks for report.

**Comment by bao-qian** [comment]
@bosam Done.

**Comment by Rictus** [comment]
Thanks a lot happlebao. Is it already available as a new release ?

**Comment by bosam** [comment]
Thank you @happlebao ! Works like a charm, I can finally enjoy the use of plugins.

**Pull request merged**
