### PR TITLE
Make some changes to SettingWindow UI

### PR DESCRIPTION
**Pull request by KennanChan**
Add icons(from icons8.cn) to tab headers.
Change some UI elements on general tab page.
Other tab pages on the way

### CODE REVIEW

**Comment by lances101** [comment]
Thank you for your PR. I will review it and if everything is fine we'll merge it.

**Comment by KennanChan** [comment]
Sorry, there is still something wrong and I am working on it. Just wait for a new commit

**Comment by jhdxr** [comment]
maybe you can add a `[WIP]` in the title if you still have some work todo, and remove it after you finish.

**Comment by KennanChan** [comment]
Got it! The work is done and you can review it. :)

**Comment by jhdxr** [comment]
merged into ui branch, thanks.

**Pull request merged**
