### PR TITLE
Extend the "Folder" plugin to enable open folder by PowerShell or Console

### PR DESCRIPTION
**Pull request by stevenxi**
Added 3 feature to the folder plugin, by adding an operator following the search query:

1. Automatic create a dated folder, would be useful for organize temporary working folder.
For example, search "Temp|d" will create/open Temp\yyyy-MM-dd as today's working folder.

2. Open the folder by Power Shell
Query "MyProject|ps"

3. Open the folder by command line console
Query "MyFolder|cmd"

### CODE REVIEW

**Comment by jhdxr** [comment]
1. could you split this into 3 PRs? one feature one PR please
2. I would merge it without doubt if opening in shells are context menu items with a setting to disable it (so non-programming users won't be affected)
3. I'd like to hear others' voice about the syntax to specify the shell. IMO there are serveral things we have to decide. e.g. why `|`? why `ps` not `powershell`?

**Comment by jhdxr** [comment]
btw, please target `dev` branch for new PRs, thanks.

**Comment by stevenxi** [comment]
Hi @jhdxr 

1. It can't be split into 3 PRs. All 3 implementations are using same provider interface, which is new. Otherwise the PRs would have dependency on each others. In the other word, although there're 3 new features, but they're pretty much the same. Also it would be easier to extend further later on. 

2. I can work on it. Although the non-programmer wouldn't even notice this change without reading the menu (sorry didn't include any). As it's not part of auto-complete.

3. Using `|` is just it's a illegal character in the file path. It won't appear in a normal legal folder paths.  Using `ps` just because it's initial for PowerShell.  我想中文文件名里也没有这个字符吧。

btw, is there anyway I can re-target the PR once open?

Thanks.

**Comment by jhdxr** [comment]
@stevenxi  thanks for the prompt reply. 
1. I see. Actually you can do it. What you have to do is first commit all the shared codes, let's say this is commit1. and based on this commit, you can create 3 different branches. Since they share the same commit (commit1), there won't be any conflict when merging.
2. I prefer context menu rather than some magic in the query string because users may not know this feature forever if no UI indicating it.
3. I'm not saying `|` or `ps` is illegal. It  just sounds like personal preference to me. so I'm asking for others opinions.

Yes you can re-target the PR, just click the `edit` button on the top right for others repos. Unfortunately, Wox has two seperate lines for `dev` and `master` (for unknown reason, at least unknown for me), so you have no choice but open a new PR. sorry.

**Comment by stevenxi** [comment]
hi @jhdxr 

1. Surely can do.
2 In this case I'd rather close this PR and keep it as my personal build.  Because I'm trying to avoid using mouse.  But you're right, it's more of my personal preference.
3. I think you misunderstood what I mean.  I chose the `|` because it's illegal. That's the answer to "why choose it".  It's due to need to use an illegal char so it won't appear in a normal search.

Thanks.

**Comment by bao-qian** [comment]
close due to no further response from author.
please open new pr in future if needed.

**Pull request closed without merging**
