### PR TITLE
Control Panel Split Logic

### PR DESCRIPTION
**Pull request by CoenraadS**

### CODE REVIEW

**Comment by CoenraadS** [comment]
Pending icon exception fix
(Everything works, but IOBit Uninstaller can't find icon..)

**Comment by CoenraadS** [comment]
Still can't figure out why IOBit doesn't return an icon (because icon pointer is found successfully), but now it doesn't crash when icon pointer exists, but icon extraction fails.

**Comment by CoenraadS** [comment]
This IOBit program is really causes a headache.

It's registered here:
`HKEY_CLASSES_ROOT\CLSID\{8DE189EC-C9C8-4D31-9F18-E0B7407019A9}\Shell\Open\command`

`(Default)` is `"C:\Program Files\IObit\IObit Uninstaller\IObitUninstaler.exe" control_statistics`

But when I run GetValue(), I get `"\"C:\\Program Files\\IObit\\IObit Uninstaller\\IObitUninstaler.exe\" control_statistics"`

Not sure how to prevent this. No other application displays this behavior
http://i.imgur.com/FHKSDpn.png.

**Comment by orzFly** [comment]
There is a method called ShellRun.

**Comment by CoenraadS** [comment]
ProcessStartInfo is not the problem, there seems to be phantom chars hidden in this registry value.

**Comment by orzFly** [comment]
Where are the  phantom chars?

**Comment by CoenraadS** [comment]
`\"` prefixed to string

**Comment by orzFly** [comment]
It's prefixed by Visual Studio Debugger and it's not the real value.

**Comment by CoenraadS** [comment]
No, see the screenshot I posted before http://i.imgur.com/FHKSDpn.png

All the other values (e.g. Java) do not have this.

**Comment by orzFly** [comment]
So you I prefer you use System.Diagnostics.Debug.WriteLine instead of Visual Studio Debugger.

**Comment by CoenraadS** [comment]
Ah you are correct, my mistake: I can't believe I spend so much time on this -_- So obvious..

**Pull request merged**
