### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pieper126**
I would like to contribute to the project. Though i'm not really certain If this is the way start contributing.

### CODE REVIEW

**Comment by bao-qian** [comment]
We still have a lot of features and bugs to resolve. Take a look at [issues page](https://github.com/Wox-launcher/Wox/issues), especially for [help_needed](https://github.com/Wox-launcher/Wox/issues?q=is%3Aopen+is%3Aissue+label%3Ahelp_needed) labeled issue. :)

**Comment by pieper126** [comment]
just that I'm sure you clone the git then make the changes and then merge them using a pull request?
or?

**Comment by bao-qian** [comment]
1. fork **master**
2. make changes
3. send pull request to **dev** branch

**Comment by pieper126** [comment]
mm it doesn't and it crashed on plugins, is that normal?

**Pull request closed without merging**
