### PR TITLE
Added Spanish language

### PR DESCRIPTION
**Pull request by DanVerseDev**

### CODE REVIEW

**Comment by bao-qian** [comment]
thanks for contribution.

**Comment by DanVerseDev** [comment]
Hi, i've noticed that only one file was checked, in the latest release, the spanish language doesn't work as it lacks two files

**Comment by bao-qian** [comment]
@DanielmGM 

could you open pr to fix this?

**Comment by DanVerseDev** [comment]
I don't know what the error is, it appears in the master branch but in the release when i click Español it shows in English

**Pull request merged**
