### PR TITLE
Translate to Norwegian Bokmål

### PR DESCRIPTION
**Pull request by 16patsle**

### CODE REVIEW

**Comment by jhdxr** [comment]
You need to register your language in `AvailableLanguages.cs`

**Comment by 16patsle** [comment]
Thanks @jhdxr! Updated the branch with another commit now.

**Comment by 16patsle** [comment]
No idea why the build failed, let me know if there is anything I need to do to fix it.

**Comment by jhdxr** [comment]
the ci failure has nothing to do with you commits, I've fixed it in master. however, there is a merge conflict. can you open a new PR targeting `dev` branch? thx.

**Comment by 16patsle** [comment]
Created #2123, so I guess I'll close this one.

**Pull request closed without merging**
