### PR TITLE
Highlighting how results matched

### PR DESCRIPTION
**Pull request by JohnTheGr8**
I have implemented highlighting to display how results matched the provided search query, taking from what was previously discussed in #116 and #441

It looks like this:

Demo
#### Details

I added two new properties to the Result class: `TitleHighlightData` and `SubTitleHighlightData`. This can be used from any plugin to highlight results, either on the title or the subtitle (or both).

We could have avoided this by matching results with FuzzyMatcher and highlighting based on that, but this introduces other problems and doesn't give plugin developers full control of how results get highlighted. This seemed like the best approach.
#### Plugins already supported

As partially shown in the demo image above, the following default plugins work with highlighting already:
- Wox.Plugin.Everything
- Wox.Plugin.PluginManagement
- Wox.Plugin.ControlPanel
- Wox.Plugin.Program
- Wox.Plugin.Sys ( _note: does not work perfectly, highlighting will not update on already displayed results_ )
#### Regarding Chinese/Pinyin

I do not understand Chinese or the Pinyin system, so I have not attempted to implement highlighting for these cases. I think it should be straight-forward enough to get it working...

Hope this is helpful!

### CODE REVIEW

**Review by mavanmanen — APPROVED** [review]
This is great, should definitely be added.

**Comment by germanoeich** [comment]
Why is this not merged yet? It's a great feature

**Comment by JohnTheGr8** [comment]
Hey,

Any update on this? 

I can resolve the conflicts when you're ready to merge, just let me know...

Cheers

**Comment by germanoeich** [comment]
@happlebao

**Comment by jjw24** [comment]
Hi guys, this feature is now added to my fork's version of Wox: https://github.com/jjw24/Wox/releases. Enjoy.

**Comment by bao-qian** [comment]
could you clean this pr?

**Comment by bao-qian** [comment]
Hi @JohnTheGr8, 
your pr has been merged in fork https://github.com/jjw24/Wox/issues/81
and all the has been merged back.

Check prs below.
https://github.com/Wox-launcher/Wox/pull/2817

for anyone want to try the new build, here is the link 
https://ci.appveyor.com/project/bao-qian/wox/builds/32316004/artifacts

@germanoeich   @mavanmanen

**Pull request closed without merging**
