### PR TITLE
Add support for multiple keywords to JsonRPC plugins

### PR DESCRIPTION
**Pull request by roose**

### CODE REVIEW

**Comment by bao-qian** [comment]
what are you trying to do with this ability?

**Comment by roose** [comment]
i want get access to action keyword from python/exe plugin, for create plugin like WebSearch, for example I have plugin for search packages on npmjs.com, I want add support for other package managers, e.g. search gulp, grunt plugins, python packages, etc, as alfred workflow https://github.com/willfarrell/alfred-pkgman-workflow

**Comment by bao-qian** [comment]
ok, I get it.
but this ability is not that easy to achieve, far more difficult than your current approach. and your way is wrong.
we need change `PluginMetadata`, 
so the settings page can read and change it
and `PluginManager` can dispatch query to properly plugin.

**Comment by bao-qian** [comment]
what I can suggest is that ask me before you want to make big changes...

**Comment by roose** [comment]
uh-oh, it's super mega feature for me :cry: will have to write many plugins for one thing (
ok, another question, can I wrote dll plugin with `C`, not `CSharp`? =) (http://getwox.com tells me I may write plugins on `Golang` and `NodeJS`=))

**Comment by bao-qian** [comment]
the dll plugins is actually CLR plugins (.net, c#, f#, ironpython etc...)
you got the executable plugin though..

**Comment by bao-qian** [comment]
it will be added in the future anyway  (#537 )

**Comment by roose** [comment]
I thought a little, you tell about redirect query by action keywords to plugins and change keywords from ui settings, but I tell about access to current keyword from plugin, any changes in plugin api don't get access to keyword from plugin, anyway you will have to add keyword in json rpc request.
I think changes keyword from ui settings for json rpc plugins don't need at all, if in plugin I check keyword and user change it in settings, how my plugin know about it?
My english is very bad ) may be I wrong explained, **sorry for importunity** =)

wox keywords

anyway you in future will have add keyword to json rpc as {”keyword”: “keyword_name”}
why not add it now as is? I know realisation isn’t pretty, but it works, and in future this part anyway will be same, changes will be affect only to plugin api settings and other e.g. plugin metadata, plugin manager etc

**Comment by bao-qian** [comment]
@roose it's complicated, if you really want to know, check the websearch plugin which implements `IMultipleActionKeywords`, you can change web search keyword to whatever you want.

because when the ui updates the keywords, the web search plugin will be called to provide the UI, so web search plugin can change internal settings.

since the UI is using WPF, I haven't figured a easy way to implement it for jsonrpc plugin.

wait two month, everything will be better....

**Comment by roose** [comment]
yes websearch plugin can use multiple keywords, but! it don't have any output results, only just opens link, if I add or change keyword it works good, but if plugin on every keyword run some different code for example for websearch parse page and show results in Wox it's will not work because plugin does not know about new or changed keyword, and anyway csharp plugin can get access to keyword

**Comment by roose** [comment]
imho ui settings for Wox is a very bad idea, ui settings for using with mouse for application which main idea not using mouse =)

**Comment by bao-qian** [comment]
oh, I see, I misunderstanding you questions.

I just found that the query in python is just a string, really bad. it should be a object.

what you could do is use a new query method instead of change the existing one (compability),
then embedded the query object in parameters. (don't need to change `JsonRPCModel`)

hmm, multiple keywords to JsonRPC plugins is easier than I thought anyway

**Comment by roose** [comment]
you about don't use `query` method in my changes and create new method e.g. `raw_query` for compatibility with old python plugins?

**Comment by happlebao** [comment]
no, you can't change name, because old plugins use that name.
try this way
C#
```
Parameters = new object[] { query.Search, query.Keyword }
```

wox.py
```
def query(self,query):
def query(self,query, keyword):
```

**Comment by bao-qian** [comment]
no, you can't change name, because old plugins use that name.
let me think about it

**Comment by roose** [comment]
hmm, if we add keyword as second parameter in parameters old python plugins stop working because now in `wox.py` we send parameters as `*request_parameters` is a tuple, and `query` method have one parameter `query` is a string, if `query` is a tuple with one item python use it as string else use as tuple, e.g.:

``` python
request_parameters = ["query"]
request_method(*request_parameters)
```

all ok, but if:

``` python
request_parameters = ["query", "keyword"]
request_method(*request_parameters)
```

error: `TypeError: query() takes exactly 2 arguments (3 given)`

because:

``` python
def query(self,query):
    return []
```

**Comment by roose** [comment]
All old python plugins should use new `wox.py` and change `query` function as:

``` python
def query(self,*query):
    keyword = query[1]
    query = query[0]
    #some code
    return results
```

**Comment by roose** [comment]
@happlebao I do not understand what you mean :smile: 
You talking about the c# method or python method? If about the c#, i don't know how to do it, if you mean create new `ExecuteQuery` method. Or you mean just send with current `ExecuteQuery -> Parameters` whole `Query` object or just `ActionKeyword`?

**Comment by bao-qian** [comment]
The bottom line is we need figured a way to do this without plugin author manually to update their plugin, so wox can maintain backward compability.

**Comment by roose** [comment]
I agree with this, but in wox.py `query` method was initially wrong handled parameters, if parameters contains more than one item it's don't work properly, will have to once change this method, and in future with this will not be any problems

**Comment by roose** [comment]
ok i close this and open new pr

**Pull request closed without merging**
