### PR TITLE
Multilingual search

### PR DESCRIPTION
**Pull request by karpovv-boris**
#1378 

Added:
* layout converter for query to all user-installed keyboard languages.
* files with all Windows keyboard layout mappings (`key` to `letter`).
  * file naming: `$"{cultureInfo.Name} {cultureInfo.LCID} {cultureInfo.EnglishName}.json"`

### CODE REVIEW

**Comment by karpovv-boris** [comment]
Demo:
git

**Comment by karpovv-boris** [comment]
#1378

**Comment by Sithell** [comment]
Amazing! This is exacttly what I was waiting for

**Comment by Sithell** [comment]
@karpovv-boris Would it be a problem for you to release an installer for your fork? I tried to build it from sources, but it crashes when trying to restart or use plugins. I'm not very good with C# and don't want to wait for PR to me merged, the fork is just so much better
Please?

**Comment by karpovv-boris** [comment]
@Sithell I can try to build it, please wait until the end of this week.
p.s. wox is dead, switch to PowerToys Run - they forked Wox. And yes, PR won't be merged here.

**Comment by karpovv-boris** [comment]
@Sithell Hey man! My attempt is failed, installation on my machine does not produce .exe file for Wox. Both for master and f/multilingual_search branches.

Screenshot_1

**Comment by karpovv-boris** [comment]
Hey @Sithell. Try this files https://github.com/karpovv-boris/Wox/releases/tag/1.5.0, maybe on your machine it will working. Seems my windows copy just doesn't work properly.

**Comment by qianlifeng** [comment]
close since https://github.com/Wox-launcher/Wox/discussions/3937

**Pull request closed without merging**
