### PR TITLE
make Wox.Plugin.Shell support bash on Windows 10

### PR DESCRIPTION
**Pull request by ZeppLu**
Windows 10 如今有三大命令行：cmd，powershell，bash。做了一点微小的工作，给装了 bash 的机器增添了一个选项。第一次写 C#，如果有问题请多多指教。

image

### CODE REVIEW

**Comment by TincanPipPip** [comment]
Is there any hope of seeing this in the wild? Would be amazing :-D

**Comment by johnbent** [comment]
Is this still active?  It would be so amazing to have this....  Looks awesome!

**Comment by jtrv** [comment]
Can we make it an option, or would it even be possible to load multiple terminals with this plugin ie. 
we could have ">" for cmd ">>" for powershell core and "$" for bash.

**Comment by bao-qian** [comment]
hi @ZeppLu 
since the conflict is not easy to resolved
your contribution has been cherrypicked https://github.com/Wox-launcher/Wox/pull/2825

**Pull request closed without merging**
