### PR TITLE
Fixes MainWindow.xaml preview

### PR DESCRIPTION
**Pull request by rmterra**
Fixes: #495

Removed all uses of VisibilityConverter and map Visibility property directly.

Also I created VisibilityExtensions as syntatic sugar to validate if prop current value is or not visible.

### CODE REVIEW

**Comment by bao-qian** [comment]
the build is not working and it has conflicts....

**Comment by rmterra** [comment]
ok, sorry I will solve it

**Comment by bao-qian** [comment]
Thanks, I didn't notice that you already fixed it.

**Comment by rmterra** [comment]
Haha no problem xD

**Pull request merged**
