### PR TITLE
Improved font rendering

### PR DESCRIPTION
**Pull request by kotcrab**
For some reason main window fonts looked unnatural, I found this SO answer https://stackoverflow.com/questions/190344/wpf-blurry-fonts-issue-solutions Results after applying fix:
Before:

Now:

Testing with Chinese characters:

After fix:

Text is more readable and clear.

### CODE REVIEW

**Comment by bao-qian** [comment]
gdi is not a good option for high dpi screen.
I'd suggest you use a sharper font: https://be5invis.github.io/Iosevka/

**Comment by kotcrab** [comment]
A lot of people still use standard screens where GDI looks better. Also I want to use standard font. Can we add this as configurable setting?

**Comment by kotcrab** [comment]
Even the Iosevka font doesn't look good with default rendering mode.

Default:

`Display` mode:

**Comment by eamodio** [comment]
Please add this -- the current font rendering looks very poor on my display (1920x1200) 100% scaling.

**Pull request closed without merging**
