### PR TITLE
Add support for multiple keywords to JsonRPC plugins #2

### PR DESCRIPTION
**Pull request by roose**

### CODE REVIEW

**Comment by roose** [comment]
@happlebao what should I fix to approve this pr?

**Comment by bao-qian** [comment]
as I said, we should maintain backward compatibility
let me propose a solution, the code may contains error (I didn't run it), but you should get the idea

1 publish wox.py as pip package
2 after install python plugin (or put it in `PythonPlugin.cs` constructor), install wox.py package using pip and remove wox.py from plugin directory
3 in new wox.py

``` python
request_method = dict(methods)[request_method_name]

if request_method_name == "query":
    q = request_parameters[0]
    try:
        results = query(q)
    catch:
        # backward compatibility
        results = query(q.search)
    print(json.dumps({"result": results}))
else:
    results = request_method(*request_parameters)

```

4 in PythonPlugin.cs

``` csharp
Parameters = new object[] { query },
```

5 in ExecutablePlugin.cs

``` csharp
Parameters = new object[] { query },
```

btw: the wox.py should be deleted from this repo, as it should be put in Wox.LanguageBinding

**Comment by roose** [comment]
I think install wox.py with `pip` isn't good idea, `pip` don't have auto update, may be Wox download `LanguageBinding` to `APPDATA`(and add to PATH for find python modules?)? And changes in `LanguageBinding` will up Wox version, and when Wox update, it update `LanguageBinding` too, what do you think about this?

**Comment by bao-qian** [comment]
we can let `wox.py` update be part of whole auto updates
add a method called `Update` in `Updater.cs`

``` csharp
Update()
{
    UpdateApp()
    UpdatePython()
    // UpdateNodejs() etc
}
UpdatePython()
{
}
```

**Comment by roose** [comment]
Oh, two versions of `pip` etc, it's hard for me =) easier create build with my changes for every update =) or don't use python plugins. May be you approve if I add this changes only for executable plugins? Then i stop using and support my python plugins

**Comment by bao-qian** [comment]
> Oh, two versions of pip etc, it's hard for me =) easier create build with my changes for every update =) 

I didn't get you.....

**Pull request closed without merging**
