### PR TITLE
Refactor MainWindow + ResultPanel with MVVM design pattern

### PR DESCRIPTION
**Pull request by LingForCC**
Implement first task in #486 

Since there are quite a lot of work to do, I refactor the MainWindow + ResultPanel with MVVM design pattern first. I did some tests. Everything looks good. But due to quite a lot of codes are modified, it is likely that I introduce some bugs. Feel free to inform me any bug.

### CODE REVIEW

**Comment by bao-qian** [comment]
Wow amazing. I don't have access to vs this week, I will test it next week.

**Comment by LingForCC** [comment]
I have been looking for this kind of tool for quite a long time. I crash into this at first sight. Have you guys got any mail group or something? So we could discuss some tech details maybe.

**Comment by bao-qian** [comment]
没这玩意。原来那个作者是中国人（现在不干了），我也是。所以一般就用 issue 和 QQ……

**Comment by LingForCC** [comment]
原来如此。你的“你也是”是指你也是中国人还是你也不干了？:) 加个qq呗。我的是285642117

**Comment by bao-qian** [comment]
当然是我也是中国人…

**Pull request closed without merging**
