### PR TITLE
Simple fixes

### PR DESCRIPTION
**Pull request by DamirAinullin**
2 simple fixes

### CODE REVIEW

**Comment by bao-qian** [comment]
1st: this will broke named arguments
2nd: what's the difference?

**Comment by bao-qian** [comment]
close due to no response

**Comment by DamirAinullin** [comment]
@happlebao Why have you closed it so quickly? Is it normal practice for this project?

**Comment by bao-qian** [comment]
Ok, reopen now.

**Comment by DamirAinullin** [comment]
Thank you.
1. I renamed Titles to Title because next line is meaningless without my change:
   this.Title = Title;
   I suppose it is just typo.
2. I just removed duplicate condition.

**Comment by bao-qian** [comment]
thanks.

**Pull request merged**
