### PR TITLE
Focuses first textbox on load

### PR DESCRIPTION
**Pull request by staff0rd**
Prior to this PR, when opening the _Add web search_ or _Add program_ forms a user needed press TAB or click the first textbox in the form to begin entering values.  This change focuses the first textbox on load, so the user can click _Add_ and then just start typing.

### CODE REVIEW

**Comment by bao-qian** [comment]
some thoughts:
1. you should use `using System.Windows.Input`, the line is just too low
2. add a simple one line comment above the code would be better

**Comment by staff0rd** [comment]
1. Ok, I'll update
2. Not sure I understand.  You'd like a comment above the line pointing out that it is selecting the first text box?

**Comment by bao-qian** [comment]
yeah, since the purpose is not obvious.

**Comment by staff0rd** [comment]
Cool, I'll update.

**Comment by staff0rd** [comment]
updates complete

**Comment by bao-qian** [comment]
I find a short way to simple way this. 1745e5c

**Pull request closed without merging**
