### PR TITLE
Translated to Spanish

### PR DESCRIPTION
**Pull request by DanVerseDev**

### CODE REVIEW

**Review by DanVerseDev — COMMENTED** [review]
Sorry i've mistaken on this

**Comment by jhdxr** [comment]
thanks for the contribution.  but please keep other language files untouched. you may want to open a new pr, or even a new branch, and cherry-pick your existing work.

**Comment by DanVerseDev** [comment]
Sorry im novice on github, I've fixed and added a feature to the sys plugin, i don't know how to separate them.
I thought that being all fixes and features involved with translation it would be ok.

The Sys plugin fix/new feature is the possibility to type commands like shutdown, reboot,etc but in the native language of each. For example, if i type Apagar (es) it would be the same that Shutdown. It's way more easy for non bilingual people

**Comment by jhdxr** [comment]
applied as 31173592ad3cbe66f2cf22b59168abbb3eeddf0f and 652f1c18a6361b15518d909bcad3c015701c639e

I've discard tranlsation for other languages in sys plugin, e.g. japanese and chinese since I can tell there are some obvious mistakes,

**Comment by jhdxr** [comment]
thanks

**Comment by DanVerseDev** [comment]
Sorry I've used Google translate. Could you translate the new entries? As it has  commands translation

**Comment by DanVerseDev** [comment]
If you don't add the new translations modified at least with Google translate, the app won't show the commands since it searches from the command in the sys plugin translations and will throw an error probably :/

**Comment by jhdxr** [comment]
it's ok. if there is no corresponding translation available, the en version will be used. so the app will still show these commands.

in addition, I'm thinking if I should revert the changes about the commands themselves in 31173592ad3cbe66f2cf22b59168abbb3eeddf0f. I agree the popup message should be translated. but since the subtitles are translated already, it might not make sense to translate the title as well.

**Comment by bao-qian** [comment]
hi, this pr has been reverted https://github.com/Wox-launcher/Wox/pull/2678  due to erroneous.
I do agree github is not a good platform for translation, I will do my best to find a better way for collaborating.

**Pull request closed without merging**
