### PR TITLE
Add 'Pause Command Prompt after command execution' option to shell plugin, and set default to false.

### PR DESCRIPTION
**Pull request by tinymins**
Add 'Pause Command Prompt after command execution' option to shell plugin, and set default to false.

### CODE REVIEW

**Comment by tinymins** [comment]
image

**Comment by tinymins** [comment]
Hello, I just rebased my branch from upstream so that some of the admin can merge it easily.

Most of the time when we press WIN+R, we just want to start something likes `> msinfo32`. Thus, we do not need to keep the console, and it's very annoying that we need to close the console manually for every single time.

**Comment by lances101** [comment]
I will merge this into dev tonight. Thank you for your PR. Next time please PR from and into dev.

**Comment by lances101** [comment]
Merged into dev as of https://github.com/Wox-launcher/Wox/commit/35368b65546bf41050fc959fdbeecf4c2e361415. Thank you for your contribution! 

Please PR from dev (or a branch with dev as base) and against dev next time so that the PR process can be done here on Github without manual merges. 

____ 

**First and foremost, my apologies.** I was a little hasty and should've asked if you would like to make a new PR against dev first as in the way I did it thecommit history only has a reference to this PR without your direct commit. Sorry. 

Changing the branch of the PR here on Github adds about 1000+ commits to merge from the master branch to dev (these, potentially, could be squashed so that they don't appear). 

If you'd like to, please do a new PR (your dev to Wox dev), I will reverse commit my own merge and accept your PR so that it's reflected in the commit history.

**Comment by tinymins** [comment]
Give me a second, and I'll do a new PR now, thanks. 😃

**Comment by jhdxr** [comment]
@lances101 next time you may try https://github.com/Wox-launcher/Wox/pull/1490.patch , git apply the patch, it will keep the author info, and you will be shown in the attribute committer.

**Pull request closed without merging**
