### PR TITLE
Fix(Tray Menu): Can not load string from translated resource.

### PR DESCRIPTION
**Pull request by cmzy**
Fix(Tray Menu): Can not load string from translated resource.

### CODE REVIEW

**Comment by bao-qian** [comment]
Sorry, I can't accept you PR now.
There is a huge refactoring for settings,
but I'm too busy(find and move home) this week to finish it.

**Comment by cmzy** [comment]
@happlebao  搬家？搬哪里去呢？

**Comment by bao-qian** [comment]
没看懂你代码，解释一下？
具体什么问题？
怎么就解决了？

**Comment by cmzy** [comment]
就是桌面Tray Menu右键菜单无论设置是否是中文，都一直是英文的。无法改成中文。

**Comment by bao-qian** [comment]
感谢汇报问题。其实这是一个初始化顺序的问题，所以不用改那里。

**Pull request closed without merging**
