### PR TITLE
refactor IsWindowFullscreen fix #687

### LINKED ISSUE #687: Wox shortcut does not work on windows 10 desktop
Firstly, many thanks for Wox! For people switching from Mac it's great to have something like alfred :-) 

Before you report any bugs try search existing issues

Done - no other issue found.
1. Please specify Wox version

1.3.67
1. Please describe the steps to **reproduce** the bug
- Press Win+D to access the windows 10 desktop.
- Press the assigned Wox shortcut (Ctrl+space) 
  -> Wox does not start. (shortcut works when other windows are open, e.g. Chrome, Explorer, etc)
1. Please provide Windows version

Windows 10
1. Please provide Exception info if you have.

No exception
1. Please provide **logs** from `%APPDATA%\Wox\Logs` if you have.

```
2016-05-24 07:17:03.1921|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|Python can't be found in PATH.
2016-05-24 07:17:03.2078|ERROR|Wox.Core.Plugin.PluginsLoader.PythonPlugins|
2016-05-24 07:17:03.3484|INFO|Wox.Plugin.Program.Main.Init|Preload 248 programs from cache
2016-05-24 07:17:06.8557|INFO|Wox.App.<OnStartup>b__8_0|Preload 200 images from cache
```
1. Please provide screenshot if you have

### PR DESCRIPTION
**Pull request by jhdxr**
this pr fix #687 , and it seems #706 was fixed as well ( I can't reproduce it any more) but I'm not sure.

### CODE REVIEW

**Comment by bao-qian** [comment]
所以开始菜单打开的时候，被误判成了 full screen 模式了？我晚上回去开个 debugger 看一下……

**Comment by jhdxr** [comment]
no, I don't think so. I have debugged for that case. so I'm curious why 706 is fixed.

btw, I'll go out for several days without my laptop. so if you have any problem you can email me directly.

**Comment by bao-qian** [comment]
我试了一下，这个 pr 在我这并没有修复 #706 
我会在修复 #706 后合并这个 pr

**Comment by bao-qian** [comment]
因为我之前 commit history 太乱了，我只能 cherry pick 了

**Pull request closed without merging**
