### PR TITLE
Add placeholder text styling (fix #2833)

### LINKED ISSUE #2833: Placeholder text color
### Are you submitting a bug report?

No

While making a theme there is no option to customize the color of placeholder text, it's always the same colour which really harms visibility even on BlurWhite theme

placeholder
suggestion

### PR DESCRIPTION
**Pull request by sausagemountain**
This works on built-in themes as I have changed them to work, but it will require minor adjustments to all custom themes

### CODE REVIEW

**Comment by bao-qian** [comment]
please leave a comment when you finish adjustment for this pr.

**Comment by sausagemountain** [comment]
I don't know what else I need to do for this, so I'm done

**Comment by bao-qian** [comment]
Hi, thanks for contribution,
but after I download the build, I found the suggestion is not align with query test

build: https://ci.appveyor.com/project/bao-qian/wox/builds/32365248/artifacts
screenshot:
image

**Comment by bao-qian** [comment]
reopen once you fixed this issue

**Pull request closed without merging**
