### PR TITLE
Program Plugin: ignored sequences

### PR DESCRIPTION
**Pull request by lances101**
Adds the ability to ignore results that correspond to a list of sequences. (#239)

For example, adding the word "uninstall" as an ignored sequence will remove all entries containing "uninstall". 

right now the filtering happens based on a `.Contains` after down-casing the string. This could be changed to regular expressions which would make this system more dynamic (I don't think the performance impact will be high). Lets discuss this possibility before accepting the PR

### CODE REVIEW

**Comment by jhdxr** [comment]
I think adding an option to support regular expression is much better, or many users without programming experience will fail to set the rules.

**Comment by lances101** [comment]
Acknowledged. Will add an option to choose if you are adding a Regex or a simple "contains" string check

**Comment by lances101** [comment]
Done. Now users have the ability to add either by a simple contains pattern or by specifying a regular expression.

**Comment by snwflake** [comment]
9 month open...I'm waiting for this since I downloaded Wox..... COME ON!
Edit: so I guess this is deprecated anyway

**Comment by jhdxr** [comment]
hi @lances101 , any chance to fix this PR? I guess you have to create a new branch and cherrypick your old commits.

**Comment by HsunGong** [comment]
感觉没人维护这个项目了，老板跑路了。还是说老板们抛弃WIndows转头Mac了？
Seems that all Contributors are tired to update this project because of `996`. Or they change Win into Mac ?

大家快来呼吁大佬更新呀！或者Merge Request也行呀！
Please call back Contributors to update this project or merge requests at least.

Windows永不为奴！Alfred 辣鸡！
Windows is better than MacOS! F-word Alfred!

**Comment by jhdxr** [comment]
@HsunGong 这个PR没法merge，你看一眼上面的commits就知道了。。。大概率得重开一个才行

**Comment by bao-qian** [comment]
hi @lances101 
thanks for your contribution, due to the conflict in this pr, your pr is cherrypicked 
https://github.com/Wox-launcher/Wox/pull/2832

@HsunGong @jhdxr @snwflake

here is the link for the latest build
https://ci.appveyor.com/project/bao-qian/wox/builds/32331680/artifacts

**Pull request closed without merging**
